server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://sh-cdb-5vlx8obm.sql.tencentcdb.com:62925/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: weijunjie-123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

#  thymeleaf:
#    prefix: classpath:/view/html/
#    suffix: .html
#    cache: false
#    mode: HTML
#    servlet:
#      content-type: text/html


  redis:
    host: 123.206.199.77
    password: weijunjie123
    port: 6379
#  mvc:
#    view:
#      suffix: .html
#      prefix: /view/html/

mybatis:
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/*.xml

#logging:
#    path: ./logs/
#    level:
#      root: debug

# ------------------参数配置----------------------------
jwt:
  secret: 21B7F3D3BA0DB022A484D83008EBB345
  id: jwt
  time: 604800000






